# docker-compose.yml
version: '3'
networks:
  todoapp-net:
services:
  pythonapp:
    image: niklafinskiy/todoapp:2.1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.todoapp
    environment:
      - PYTHONBUFFERED=1
    networks:
      - todoapp-net
    depends_on:
      - mysql
    restart: unless-stopped
  mysql:
    image: niklafinskiy/mysql-local:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: my-sql
    ports:
      - "3306:3306"
    volumes:
      - todoapp-db-data:/var/lib/mysql
    env_file:
      - .env.db
    networks:
      - todoapp-net
volumes:
  todoapp-db-data:
